### ISSUE TITLE
Build doesn't recover from a failed HAML syntax parse

### ISSUE THREAD

**Issue by devraj** [anomaly/jekyll-tilt#1]
- [X] I tried updating to the latest version.
  - [ ] I can't, there is an issue.
- [ ] I Am on Windows
  - [ ] Ubuntu Bash on Windows
  - [ ] Fedora Bash on Windows
  - [ ] Other  Bash on Windows
- [ ] I Am on Linux
  - [ ] Ubuntu
  - [ ] Fedora
- [X] I Am on macOS
- [ ] I'm on Docker
  - [ ] I understand Docker may be unsupported.

## Steps

- Save a HAML file when the syntax is broken

## Output

```sh
#<Thread:0x00007f913048e518@/Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
	34: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/listen-3.1.5/lib/listen/internals/thread_pool.rb:6:in `block in add'
	33: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/listen-3.1.5/lib/listen/event/loop.rb:42:in `block in setup'
	32: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/listen-3.1.5/lib/listen/event/loop.rb:84:in `_wait_for_changes'
	31: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop_for'
	30: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/listen-3.1.5/lib/listen/event/processor.rb:15:in `loop'
	29: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/listen-3.1.5/lib/listen/event/processor.rb:19:in `block in loop_for'
	28: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/listen-3.1.5/lib/listen/event/processor.rb:115:in `_process_changes'
	27: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/listen-3.1.5/lib/listen/event/config.rb:23:in `call'
	26: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/jekyll-watch-2.0.0/lib/jekyll/watcher.rb:66:in `block in listen_handler'
	25: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/jekyll-watch-2.0.0/lib/jekyll/watcher.rb:125:in `process'
	24: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/jekyll-3.8.3/lib/jekyll/site.rb:71:in `process'
	23: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/jekyll-3.8.3/lib/jekyll/site.rb:192:in `render'
	22: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/jekyll-3.8.3/lib/jekyll/site.rb:471:in `render_pages'
	21: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/jekyll-3.8.3/lib/jekyll/site.rb:471:in `each'
	20: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/jekyll-3.8.3/lib/jekyll/site.rb:472:in `block in render_pages'
	19: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/jekyll-3.8.3/lib/jekyll/site.rb:479:in `render_regenerated'
	18: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/jekyll-3.8.3/lib/jekyll/renderer.rb:60:in `run'
	17: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/jekyll-3.8.3/lib/jekyll/page.rb:180:in `trigger_hooks'
	16: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/jekyll-3.8.3/lib/jekyll/hooks.rb:102:in `trigger'
	15: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/jekyll-3.8.3/lib/jekyll/hooks.rb:102:in `each'
	14: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/jekyll-3.8.3/lib/jekyll/hooks.rb:103:in `block in trigger'
	13: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/jekyll-tilt-1.0.5/lib/jekyll/tilt.rb:23:in `block in setup!'
	12: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/jekyll-tilt-1.0.5/lib/jekyll/tilt.rb:46:in `convert_d!'
	11: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/jekyll-tilt-1.0.5/lib/jekyll/tilt/processor.rb:52:in `run_for'
	10: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/jekyll-tilt-1.0.5/lib/jekyll/tilt/processor.rb:52:in `each'
	 9: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/jekyll-tilt-1.0.5/lib/jekyll/tilt/processor.rb:53:in `block in run_for'
	 8: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/jekyll-tilt-1.0.5/lib/jekyll/tilt/processors/haml.rb:12:in `run_for'
	 7: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/tilt-2.0.8/lib/tilt/template.rb:109:in `render'
	 6: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/tilt-2.0.8/lib/tilt/haml.rb:24:in `evaluate'
	 5: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/tilt-2.0.8/lib/tilt/template.rb:169:in `evaluate'
	 4: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/tilt-2.0.8/lib/tilt/template.rb:235:in `compiled_method'
	 3: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/tilt-2.0.8/lib/tilt/template.rb:235:in `synchronize'
	 2: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/tilt-2.0.8/lib/tilt/template.rb:236:in `block in compiled_method'
	 1: from /Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/tilt-2.0.8/lib/tilt/template.rb:274:in `compile_template_method'
/Users/devraj/Work/WebApps/wattle-website/vendor/bundle/ruby/2.5.0/gems/tilt-2.0.8/lib/tilt/template.rb:274:in `class_eval': (__TEMPLATE__):26: unknown type of %string (SyntaxError)
...=>"{{ post.date | date: "%Y-%m-%d" }}")).to_s);; _hamlout.bu...
...                            ^~~
(__TEMPLATE__):26: syntax error, unexpected end-of-input
...=>"{{ post.date | date: "%Y-%m-%d" }}")).to_s);; _hamlout.bu...
...                            ^~~
^C
```

## Expected

The build succeeds and the site reloads the next time around.

**Comment by envygeeks** [comment]
Hmm.. normally Jekyll will catch all errors, I wonder if they changed something, or if we need to force the thread bubble, which should really be something that Tilt does (as is policy) but we should be able to work around this here, I'll take a look this weekend.
